### ISSUE TITLE
Cannot run action

### ISSUE THREAD

**Issue by ichistmeinname** [harehare/elm-analyse-action#1]
I use your action in my workflow as follows.

```
  elm-analyse:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    steps:
    - uses: actions/checkout@v2

    - uses: harehare/elm-analyse-action@v1
      with:
        elm_analyse_version: 0.16.5
        ignore_error: true
        working_directory: src
```

When running the pipeline, I get the follow error message.

```
##[error](t || "").replace is not a function
```

As a side-note: the README uses the wrong name for the GitHub action (`elm-action` instead of `elm-analyse-action`).
